org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.0.1-beta
neo_version_range=[26.1.0.1-beta,)

# Mod Properties
mod_version=3.0.0

# Dependency Properties
atlasviewer_coord=7806148
atlasviewer_version=16.0.0
morered_mc_version=1.21
morered_version=6.0.0.0
